package com.unimib.assignment3.POJO;

import com.unimib.assignment3.enums.TaskState;
import jakarta.persistence.*;
import java.time.LocalDate;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import com.unimib.assignment3.constants.*;

/**
 * Task entity class.
 * <p>
 * Represents an activity with a unique identifier, a state,
 * a time range, an associated team, and a list of assigned employees.
 */
@Entity(name="task")
public class Task implements Serializable {

    /**
     * Task ID.
     * Generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long taskId;

    /** Description of the task.
     */
    @Column(name = "description")
    private String description;

    /**
     * Current state of the task.
     * Enumerated as a string in the database.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "task_state")
    private TaskState taskState;

    /**
     * Start date of the task.
     */
    @Column(name = "start_date")
    private LocalDate startDate;

    /**
     * End date of the task.
     */
    @Column(name = "end_date")
    private LocalDate endDate;

    /**
     * List of employees assigned to this task.
     * Mapped via the 'assignedEmployees' join table.
     */
    @ManyToMany
    @JoinTable(
            name = "assignedEmployees",
            joinColumns = @JoinColumn(name = "taskId"),
            inverseJoinColumns = @JoinColumn(name = "personId")
    )
    private List<Employee> assignedEmployees = new ArrayList<>();

    /**
     * Team assigned to the task.
     * Mapped by the 'teamTask' field.
     */
    @ManyToOne
    @JoinColumn(name = "teamId")
    private Team teamTask;

    /**
     * Default constructor.
     * Initializes the task state STARTED.
     */
    protected Task() {
        this.taskState = TaskState.STARTED;

    }

    /**
     * Constructor with task state.
     *
     * @param taskState the state to assign (defaults to STARTED if null)
     */
    public Task(TaskState taskState) {
        this.taskState = taskState != null ? taskState : TaskState.STARTED;
        this.startDate = LocalDate.now();
    }

    /**
     * Constructor with employees, state, and dates.
     *
     * @param assignedEmployees the list of employees to assign
     * @param taskState the state of the task
     * @param startDate the start date
     * @param endDate the end date
     */
    public Task(List<Employee> assignedEmployees, TaskState taskState, LocalDate startDate, LocalDate endDate) {
        this.assignedEmployees = assignedEmployees != null ? assignedEmployees : new ArrayList<>();
        this.taskState = taskState != null ? taskState : TaskState.STARTED;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    /**
     * Getter for task ID.
     *
     * @return the task ID
     */
    public Long getTaskId() {
        return taskId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for assigned employees.
     * Returns a copy of the list to maintain encapsulation.
     *
     * @return a new list containing assigned employees
     */
    public List<Employee> getAssignedEmployees() {
        return new ArrayList<>(assignedEmployees);
    }

    /**
     * Setter for assigned employees.
     *
     * @param dipendentiAssegnati the list of employees to set
     */
    public void setAssignedEmployees(List<Employee> dipendentiAssegnati) {
        this.assignedEmployees = dipendentiAssegnati != null ? dipendentiAssegnati : new ArrayList<>();
    }

    /**
     * Getter for task state.
     *
     * @return the current task state
     */
    public TaskState getTaskState() {
        return taskState;
    }

    /**
     * Setter for task state.
     *
     * @param taskState the task state to set
     */
    public void setTaskState(TaskState taskState) {
        this.taskState = taskState;
    }

    /**
     * Assigns an employee to the task.
     * Manages the bidirectional relationship by adding the task to the employee's list.
     *
     * @param employee the employee to add
     */
    public void assignEmployee(Employee employee) {
        if (employee == null) return;

        if (!this.assignedEmployees.contains(employee)) {
            this.assignedEmployees.add(employee);
            employee.getTasks().add(this);
        }
    }

    /**
     * Removes an employee from the task.
     * Manages the bidirectional relationship by removing the task from the employee's list.
     *
     * @param employee the employee to remove
     */
    public void removeEmployee(Employee employee) {
        if (employee == null) return;

        if (this.assignedEmployees.remove(employee)) {
            employee.getTasks().remove(this);
        }
    }

    /**
     * Checks if an employee is assigned to this task.
     *
     * @param employee the employee to check
     * @return true if present, false otherwise
     */
    public boolean hasEmployee(Employee employee) {
        return this.assignedEmployees.contains(employee);
    }

    /**
     * Getter for start date.
     *
     * @return the start date
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Setter for start date.
     * Validates that the start date is not after the end date.
     *
     * @param startDate the start date to set
     * @throws IllegalArgumentException if start date is after end date
     */
    public void setStartDate(LocalDate startDate) {
        if (startDate != null && this.endDate != null && startDate.isAfter(this.endDate)) {
            throw new IllegalArgumentException(TaskConstants.START_DATE_AFTER_END);
        }
        this.startDate = startDate;
    }

    /**
     * Getter for end date.
     *
     * @return the end date
     */
    public LocalDate getEndDate() {
        return endDate;
    }


    /**
     * Setter for end date.
     * Validates that the end date is not before the start date.
     *
     * @param endDate the end date to set
     * @throws IllegalArgumentException if end date is before start date
     */
    public void setEndDate(LocalDate endDate) {
        if (endDate != null && this.startDate != null && endDate.isBefore(this.startDate)) {
            throw new IllegalArgumentException(TaskConstants.END_DATE_BEFORE_START);
        }
        this.endDate = endDate;
    }

    /**
     * Retrieves IDs of all assigned employees.
     *
     * @return a list of employee IDs
     */
    public List<Long> getAllEmployeesId() {
        List<Long> idDipendenti = new ArrayList<>();
        for (Employee employee : assignedEmployees) {
            idDipendenti.add(employee.getPersonId());
        }
        return idDipendenti;
    }

    /**
     * Getter for the associated team.
     *
     * @return the team assigned to the task
     */
    public Team getTeamTask() {
        return teamTask;
    }

    /**
     * Setter for the associated team.
     *
     * @param team the team to set
     */
    public void setTeamTask(Team team) {
        this.teamTask = team;
    }

    /**
     * toString method.
     *
     * @return a string representation of the task
     */
    @Override
    public String toString() {
        String idTeam = teamTask != null ? teamTask.getTeamId().toString() : "null";
        return "Task{" +
                "task id=" + taskId +
                ", assigned employees=" + getAllEmployeesId() +
                ", start date=" + startDate +
                ", end date=" + endDate +
                ", task state=" + taskState +
                ", team=" + idTeam +
                '}';
    }

    /**
     * Equals method based on task ID.
     *
     * @param o the object to compare
     * @return true if IDs match
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Task task)) return false;
        return taskId != null && taskId.equals(task.getTaskId());
    }

    /**
     * HashCode method.
     *
     * @return the class hash code
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
