package com.unimib.assignment3.POJO;

import jakarta.persistence.*;

import java.util.ArrayList;
import java.util.List;

/**
 * Team entity class.
 * <p>
 * Represents a team with a unique identifier, a list of employees,
 * a supervisor, and a list of tasks.
 * </p>
 */
@Entity(name="team")
public class Team {
    /**
     * Team ID.
     * Generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long teamId;

    // orphan removal not necessary as the deletion of a team does not imply
    // the deletion of the associated employees
    /**
     * List of employees in the team.
     * Mapped by the 'employeeTeam' field in the Employee entity.
     * Orphan removal is not necessary as the deletion of an employee does not imply
     * the deletion of the associated team.
     */
    @OneToMany(mappedBy = "employeeTeam", cascade = CascadeType.MERGE)
    private List<Employee> employees = new ArrayList<>();

    /**
     * Supervisor of the team.
     * Mapped by the 'supervisor' field in the Supervisor entity.
     */
    @ManyToOne
    @JoinColumn(
            name = "team_supervisor_id",
            foreignKey = @ForeignKey(name = "fk_team_supervisor")
    )
    private Supervisor supervisor;

    /**
     * List of tasks assigned to the team.
     * Mapped by the 'teamTask' field in the Task entity.
     * Orphan removal is not necessary as the deletion of a task does not imply
     * the deletion of the associated team.
     */
    @OneToMany(mappedBy = "teamTask", cascade = CascadeType.MERGE)
    private List<Task> tasks = new ArrayList<>();

    /**
     * Default constructor.
     */
    protected Team() {
    }

    /**
     * Constructor with supervisor.
     * Use Supervisor.addTeamsSupervisionato to manage the relationship bidirectionally.
     *
     * @param supervisor the supervisor of the team
     */
    public Team(Supervisor supervisor) {
        supervisor.addSupervisedTeam(this);
    }

    /**
     * Constructor with employees and supervisor.
     *
     * @param employees the employees of the team
     * @param supervisor the supervisor of the team
     */
    public Team(List<Employee> employees, Supervisor supervisor) {
        setEmployees(employees);
        supervisor.addSupervisedTeam(this);
    }

    /**
     * Constructor with employees, supervisor and tasks.
     *
     * @param employees the employees of the team
     * @param supervisor the supervisor of the team
     * @param tasks the tasks assigned to the team
     */
    public Team(List<Employee> employees, Supervisor supervisor, List<Task> tasks) {
        setEmployees(employees);
        supervisor.addSupervisedTeam(this);
        setTasks(tasks);
    }

    /**
     * Getter for team ID.
     *
     * @return the team ID
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * Getter for employees.
     *
     * @return the list of employees
     */
    public List<Employee> getEmployees() {
        return employees;
    }

    /**
     * Setter for employees.
     * Sets the list of employees for the team adding the relationship bidirectionally.
     * For programming design reasons, this setter is used only within the class to manage
     * the bidirectional relationship. Outside the class, to add a list of employees,
     * a loop with addEmployee is used.
     *
     * @param employees the employees to set
     */
    private void setEmployees(List<Employee> employees) {
        removeAllEmployees();
        for(Employee employee : employees) {
            employee.setEmployeeTeam(this);
        }
        this.employees = employees;
    }

    /**
     * Setter for one employee.
     * Used by addEmployee to add one employee.
     *
     * @param employee the employee to add
     */
    private void setEmployee(Employee employee) {
        this.employees.add(employee);
    }

    /**
     * Adds an employee to the team.
     * If the employee is already in the team, it is not added again.
     * Use setEmployee to add one employee and manage the relationship bidirectionally.
     *
     * @param employee the employee to add
     */
    public void addEmployee(Employee employee) {
        if(!employees.contains(employee)){
            setEmployee(employee);
            employee.setEmployeeTeam(this);
        }
    }

    /**
     * Removes all employees from the team.
     * Removes the relationship bidirectionally between employees and teams and clears the list.
     */
    public void removeAllEmployees() {
        for(Employee employee : employees) {
            employee.setEmployeeTeam(null);
        }
        employees.clear();
    }

    /**
     * Removes an employee from the team.
     * Removes the relationship bidirectionally between employee and team.
     *
     * @param employee the employee to remove
     */
    public void removeEmployee(Employee employee) {
        if(employees.remove(employee)){
            employee.setEmployeeTeam(null);
        }
    }

    /**
     * Getter for supervisor.
     *
     * @return the supervisor
     */
    public Supervisor getSupervisor() {
        return supervisor;
    }

    /**
     * Sets the supervisor of the team.
     * Does not manage the relationship bidirectionally between supervisor and teams.
     * It is used by the Supervisor class to manage the relationship bidirectionally.
     *
     * @param supervisor the supervisor to set
     */
    public void setSupervisor(Supervisor supervisor) {
        this.supervisor = supervisor;
    }

    /**
     * Getter for tasks.
     *
     * @return the list of tasks
     */
    public List<Task> getTasks() {
        return tasks;
    }

    /**
     * Setter for tasks.
     * Sets the list of tasks for the team adding the relationship bidirectionally.
     * For programming design reasons, this setter is used only within the class to manage
     * the bidirectional relationship. Outside the class, to add a list of tasks,
     * a loop with addEmployee is used.
     *
     * @param tasks the tasks to set
     */
    private void setTasks(List<Task> tasks) {
        removeAllTasks();
        for(Task task : tasks) {
            task.setTeamTask(this);
        }
        this.tasks = tasks;
    }

    /**
     * Setter for one task.
     * Used by addTask to add one task.
     *
     * @param task the task to add
     */
    private void setTask(Task task) {
        this.tasks.add(task);
    }

    /**
     * Adds a task to the team.
     * If the task is already in the team, it is not added again.
     * Use setTask to add one task and manage the relationship bidirectionally.
     *
     * @param task the task to add
     */
    public void addTask(Task task) {
        if(!tasks.contains(task)){
            setTask(task);
            task.setTeamTask(this);
        }
    }

    /**
     * Removes all tasks from the team.
     * Removes the relationship bidirectionally between tasks and teams and clears the list.
     */
    public void removeAllTasks() {
        for(Task task : tasks) {
            task.setTeamTask(null);
        }
        tasks.clear();
    }

    /**
     * Removes a task from the team.
     * Removes the relationship bidirectionally between task and team.
     *
     * @param task the task to remove
     */
    public void removeTask(Task task) {
        if(tasks.remove(task)){
            task.setTeamTask(null);
        }
    }

    /**
     * toString method.
     *
     * @return a string representation of the team
     */
    @Override
    public String toString() {
        return "Team{" +
                "team id=" + teamId +
                ", employees=" + employees +
                ", supervisor=" + supervisor +
                ", tasks=" + tasks +
                '}';
    }
}
